"""Initial Sentinel Schema

Revision ID: 30fe41f45609
Revises: 
Create Date: 2026-04-25 17:31:54.105373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30fe41f45609'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'RESPONDER', 'ADMIN', 'API_CLIENT', name='audit_actor_type_enum', create_constraint=True), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('chain_of_custody_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'HASHED', 'UPLOADED', 'ACCESSED', 'SHARED', 'SEALED', 'RETENTION_EXTENDED', 'DELETED', name='custody_action_enum', create_constraint=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'RESPONDER', 'ADMIN', 'LEGAL', name='custody_actor_type_enum', create_constraint=True), nullable=False),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=512), nullable=True),
    sa.Column('entity_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_of_custody_log')),
    sa.UniqueConstraint('entry_hash', name=op.f('uq_chain_of_custody_log_entry_hash'))
    )
    op.create_index(op.f('ix_chain_of_custody_log_entity_id'), 'chain_of_custody_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_chain_of_custody_log_entity_type'), 'chain_of_custody_log', ['entity_type'], unique=False)
    op.create_table('responder_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responder_tiers'))
    )
    op.create_index(op.f('ix_responder_tiers_code'), 'responder_tiers', ['code'], unique=True)
    op.create_table('threat_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severity_enum', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_types'))
    )
    op.create_index(op.f('ix_threat_types_code'), 'threat_types', ['code'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone_type', sa.Enum('BUILDING', 'FLOOR', 'PERIMETER', 'PARKING', 'OUTDOOR', 'ENTRANCE', 'RESTRICTED', name='zone_type_enum', create_constraint=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('boundary_polygon', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_zone_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_zone_id'], ['zones.id'], name=op.f('fk_zones_parent_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones'))
    )
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=False)
    op.create_table('automated_playbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('threat_type_id', sa.UUID(), nullable=True),
    sa.Column('min_severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severity_enum', create_constraint=True), nullable=True),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['threat_type_id'], ['threat_types.id'], name=op.f('fk_automated_playbooks_threat_type_id_threat_types'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automated_playbooks')),
    sa.UniqueConstraint('name', name=op.f('uq_automated_playbooks_name'))
    )
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rtsp_url', sa.String(length=1024), nullable=False),
    sa.Column('camera_type', sa.Enum('FIXED', 'PTZ', 'THERMAL', 'DOME', 'BULLET', name='camera_type_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'MAINTENANCE', 'ERROR', name='camera_status_enum', create_constraint=True), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_cameras_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=False)
    op.create_index(op.f('ix_cameras_zone_id'), 'cameras', ['zone_id'], unique=False)
    op.create_table('escalation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('threat_type_id', sa.UUID(), nullable=False),
    sa.Column('min_severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severity_enum', create_constraint=True), nullable=False),
    sa.Column('responder_tier_id', sa.UUID(), nullable=False),
    sa.Column('sla_seconds', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('notification_channels', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responder_tier_id'], ['responder_tiers.id'], name=op.f('fk_escalation_rules_responder_tier_id_responder_tiers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_type_id'], ['threat_types.id'], name=op.f('fk_escalation_rules_threat_type_id_threat_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_escalation_rules_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_rules'))
    )
    op.create_index(op.f('ix_escalation_rules_responder_tier_id'), 'escalation_rules', ['responder_tier_id'], unique=False)
    op.create_index(op.f('ix_escalation_rules_threat_type_id'), 'escalation_rules', ['threat_type_id'], unique=False)
    op.create_table('responders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_on_duty', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['responder_tiers.id'], name=op.f('fk_responders_tier_id_responder_tiers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_responders_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responders'))
    )
    op.create_index(op.f('ix_responders_employee_id'), 'responders', ['employee_id'], unique=True)
    op.create_index(op.f('ix_responders_tier_id'), 'responders', ['tier_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_number', sa.String(length=64), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('threat_type_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severity_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'ESCALATED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'FALSE_ALARM', 'CLOSED', name='incident_status_enum', create_constraint=True), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('ai_model_version', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=False),
    sa.Column('gps_longitude', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_incidents_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_type_id'], ['threat_types.id'], name=op.f('fk_incidents_threat_type_id_threat_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_incidents_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_camera_id'), 'incidents', ['camera_id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_number'), 'incidents', ['incident_number'], unique=True)
    op.create_index(op.f('ix_incidents_threat_type_id'), 'incidents', ['threat_type_id'], unique=False)
    op.create_index(op.f('ix_incidents_zone_id'), 'incidents', ['zone_id'], unique=False)
    op.create_table('escalation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('escalation_rule_id', sa.UUID(), nullable=False),
    sa.Column('responder_tier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'ACKNOWLEDGED', 'ESCALATED', 'TIMED_OUT', 'CANCELLED', name='escalation_status_enum', create_constraint=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['responders.id'], name=op.f('fk_escalation_actions_acknowledged_by_id_responders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalation_rule_id'], ['escalation_rules.id'], name=op.f('fk_escalation_actions_escalation_rule_id_escalation_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_escalation_actions_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_tier_id'], ['responder_tiers.id'], name=op.f('fk_escalation_actions_responder_tier_id_responder_tiers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_actions'))
    )
    op.create_index(op.f('ix_escalation_actions_incident_id'), 'escalation_actions', ['incident_id'], unique=False)
    op.create_table('evidence_clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('pre_event_buffer_seconds', sa.Float(), nullable=False),
    sa.Column('post_event_buffer_seconds', sa.Float(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RECORDING', 'UPLOADING', 'AVAILABLE', 'SEALED', 'DELETED', name='evidence_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_evidence_clips_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_evidence_clips_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_clips'))
    )
    op.create_index(op.f('ix_evidence_clips_incident_id'), 'evidence_clips', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidence_clips_sha256_hash'), 'evidence_clips', ['sha256_hash'], unique=False)
    op.create_table('incident_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bounding_boxes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('skeleton_keypoints', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('heatmap_uri', sa.String(length=1024), nullable=True),
    sa.Column('raw_frame_uri', sa.String(length=1024), nullable=True),
    sa.Column('ai_model_version', sa.String(length=64), nullable=False),
    sa.Column('inference_time_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_detections_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_detections'))
    )
    op.create_index(op.f('ix_incident_detections_incident_id'), 'incident_detections', ['incident_id'], unique=False)
    op.create_table('playbook_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='playbook_status_enum', create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steps_completed', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_playbook_executions_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['automated_playbooks.id'], name=op.f('fk_playbook_executions_playbook_id_automated_playbooks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook_executions'))
    )
    op.create_index(op.f('ix_playbook_executions_incident_id'), 'playbook_executions', ['incident_id'], unique=False)
    op.create_table('evidence_clip_access_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_clip_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'RESPONDER', 'ADMIN', 'LEGAL', name='actor_type_enum', create_constraint=True), nullable=False),
    sa.Column('action', sa.Enum('VIEWED', 'DOWNLOADED', 'SHARED', 'EXPORTED', name='evidence_access_action_enum', create_constraint=True), nullable=False),
    sa.Column('actor_ip', sa.String(length=45), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['evidence_clip_id'], ['evidence_clips.id'], name=op.f('fk_evidence_clip_access_log_evidence_clip_id_evidence_clips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_clip_access_log'))
    )
    op.create_index(op.f('ix_evidence_clip_access_log_evidence_clip_id'), 'evidence_clip_access_log', ['evidence_clip_id'], unique=False)
    op.create_table('incident_acknowledgements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('escalation_action_id', sa.UUID(), nullable=False),
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('device_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['escalation_action_id'], ['escalation_actions.id'], name=op.f('fk_incident_acknowledgements_escalation_action_id_escalation_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_acknowledgements_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], name=op.f('fk_incident_acknowledgements_responder_id_responders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_acknowledgements'))
    )
    op.create_index(op.f('ix_incident_acknowledgements_incident_id'), 'incident_acknowledgements', ['incident_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escalation_action_id', sa.UUID(), nullable=True),
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('FCM', 'SMS', 'VOICE', 'EMAIL', name='notification_channel_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'REJECTED', name='notification_status_enum', create_constraint=True), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['escalation_action_id'], ['escalation_actions.id'], name=op.f('fk_notification_log_escalation_action_id_escalation_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], name=op.f('fk_notification_log_responder_id_responders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_log'))
    )
    op.create_index(op.f('ix_notification_log_escalation_action_id'), 'notification_log', ['escalation_action_id'], unique=False)
    op.create_index(op.f('ix_notification_log_responder_id'), 'notification_log', ['responder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_log_responder_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_escalation_action_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_incident_acknowledgements_incident_id'), table_name='incident_acknowledgements')
    op.drop_table('incident_acknowledgements')
    op.drop_index(op.f('ix_evidence_clip_access_log_evidence_clip_id'), table_name='evidence_clip_access_log')
    op.drop_table('evidence_clip_access_log')
    op.drop_index(op.f('ix_playbook_executions_incident_id'), table_name='playbook_executions')
    op.drop_table('playbook_executions')
    op.drop_index(op.f('ix_incident_detections_incident_id'), table_name='incident_detections')
    op.drop_table('incident_detections')
    op.drop_index(op.f('ix_evidence_clips_sha256_hash'), table_name='evidence_clips')
    op.drop_index(op.f('ix_evidence_clips_incident_id'), table_name='evidence_clips')
    op.drop_table('evidence_clips')
    op.drop_index(op.f('ix_escalation_actions_incident_id'), table_name='escalation_actions')
    op.drop_table('escalation_actions')
    op.drop_index(op.f('ix_incidents_zone_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_threat_type_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_number'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_camera_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_responders_tier_id'), table_name='responders')
    op.drop_index(op.f('ix_responders_employee_id'), table_name='responders')
    op.drop_table('responders')
    op.drop_index(op.f('ix_escalation_rules_threat_type_id'), table_name='escalation_rules')
    op.drop_index(op.f('ix_escalation_rules_responder_tier_id'), table_name='escalation_rules')
    op.drop_table('escalation_rules')
    op.drop_index(op.f('ix_cameras_zone_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_table('automated_playbooks')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_threat_types_code'), table_name='threat_types')
    op.drop_table('threat_types')
    op.drop_index(op.f('ix_responder_tiers_code'), table_name='responder_tiers')
    op.drop_table('responder_tiers')
    op.drop_index(op.f('ix_chain_of_custody_log_entity_type'), table_name='chain_of_custody_log')
    op.drop_index(op.f('ix_chain_of_custody_log_entity_id'), table_name='chain_of_custody_log')
    op.drop_table('chain_of_custody_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
