"""Add contact_number to EmergencyOffice

Revision ID: 577b232ef348
Revises: 7a0047d95c92
Create Date: 2026-04-29 13:54:30.573227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577b232ef348'
down_revision: Union[str, None] = '7a0047d95c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_offices', sa.Column('contact_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency_offices', 'contact_number')
    # ### end Alembic commands ###
